#230: ruff rule B905: add strict keyword to zip
MannLabs/alphadia pull request #246
Opened 2024-06-20 20:09 UTC by mschwoer

As discussed: use "strict=True" for all zips.

2024-06-21 08:09 UTC, GeorgWa requested changes

2024-06-21 08:09 UTC, GeorgWa commented on alphadia/features.py
zip( strict=True) is not yet supported by numba https://github.com/numba/numba/issues/8943
I will mark the files

2024-06-21 08:09 UTC, GeorgWa commented on alphadia/peakgroup/search.py
numba

2024-06-21 12:37 UTC, GeorgWa approved these changes
LGTM

2024-06-22 17:42 UTC, jalew188 commented
This should be applied to all AlphaX if necessary

2024-06-24 09:18 UTC, GeorgWa approved these changes

2024-06-24 10:53 UTC, merged